[32]Roll over system
froggies-studio/froggies-game pull request #24
Opened 2023-05-13 18:10 UTC by AndrewMikhaylov

2023-05-15 17:31 UTC, Marichellka commented
please add ticket number to PR name

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Scripts/Animation/PlayerAnimationState.cs
> +        RollOver = 2,
please remove index as they go by default

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Prefabs/Scene/BasicScenePrefab.prefab
please update prefab with new items

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Scripts/Core/GlobalSceneManager.cs
> +        [SerializeField] public PlayerData playerData;
Why do we need it public? (Haven't seen where it used)
Can you somehow get it from player instead?

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Scripts/Core/GlobalSceneManager.cs
> +         private void InitializeItemFactory(BasicEntity player)
????
please revert these changes

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Scripts/Core/GlobalSceneManager.cs
> +         private void InitializePotionSystem(List<ItemDescriptor> itemDescriptors, BasicEntity player)
same here

2023-05-15 17:44 UTC, Marichellka commented on Frogies-Project/Assets/Scripts/Fighting/DamageReceiver.cs
> +            // if (GlobalSceneManager.Instance.playerData.DirectionalMover.IsDashing)
why do we need it commented? remove / uncomment or add comment why it's needed

2023-05-15 17:50 UTC, Marichellka commented
feature isn't working at all

2023-05-16 15:03 UTC, Sorpirit requested changes
Also make sure that roll over auto cancels when player hits a wall

2023-05-24 20:42 UTC, vakor03 approved these changes

2023-05-24 20:42 UTC, Sorpirit approved these changes

2023-05-24 20:43 UTC, merged