FORG-93 Add knock back for enemies and player
froggies-studio/froggies-game pull request #50
Opened 2023-06-03 05:04 UTC by Sorpirit

2023-06-05 13:17 UTC, Marichellka requested changes
Please merge branch with FORG-87 to ensure that knockback is working for all enemies as you also changed a goblin prefab

2023-06-05 13:19 UTC, Marichellka commented
knock back on player doesn't work. On goblins works fine

2023-06-06 11:30 UTC, Marichellka approved these changes

2023-06-06 11:31 UTC, AndrewMikhaylov approved these changes

2023-06-06 11:31 UTC, vakor03 approved these changes

2023-06-06 11:31 UTC, merged